[project]
name = "scisoftdev-tmp-HiPOP" # TODO Project name modified to test deployment, to restore.
version = "1.0.4" # TODO Project version modified to test deployment, to restore.
description = "High Performance Optimal Path module"
readme = "README.md"
requires-python = ">= 3.10"
license = "LGPL-3.0-only"
license-files = ["LICENSE"]
# TODO authors/maintainers
keywords = [
    "graph",
    "graph-theory",
    "shortest-path",
    "dijkstra",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
]

[project.urls]
Repository = "https://github.com/EMob-Lab/HiPOP"
Issues = "https://github.com/EMob-Lab/HiPOP/issues"

[dependency-groups]
build = [ # Dependencies needed for build tasks. Must be maintained identical to "build-system".requires
    "scikit-build-core >= 1.0",
    "pybind11 >= 3.1",
]
test = [ # Dependencies needed for test tasks. Must be maintained identical to tool.cibuildwheel."test-requires"
    "pytest >= 9.1",
]
dev = [ # All dependencies needed for development tasks.
    { include-group = "build" },
    { include-group = "test" },
]
distrib = [ # Dependencies needed to build distribution files (wheels & source distributions).
    "build >= 1.6",
    "cibuildwheel >= 4.2",
]

[build-system]
requires = [ # Must be maintained identical to "dependency-groups".build
    "scikit-build-core >= 1.0",
    "pybind11 >= 3.1",
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
wheel.packages = ["python/hipop"] # Location of the pure Python package to include in the wheel...
wheel.exclude = [
    "**/*.cpp",                   # ... but the C++ sources of the wrapper must be excluded...
    "**/*.py.template",           # ... and so are the templates of the dynamically-generated Python files.
]
build-dir = "build-scikit"
editable.verbose = true
editable.rebuild = true

[tool.scikit-build.cmake.define]
HIPOP_WITH_PYTHON = "ON"
HIPOP_WITH_TESTS = "OFF"
HIPOP_WITH_EXAMPLES = "OFF"

[[tool.scikit-build.generate]]
path = "hipop/__init__.py"
template-path = "python/hipop/__init__.py.template"

[tool.cibuildwheel]
build = [ # Build Linux + Win for x64, and MacOS for ARM64. TODO is it enough?
    "*-manylinux_x86_64",
    "*-win_amd64",
    "*-macosx_arm64",
]
skip = [
    "cp3??t-*", # Free-threaded standard interpreter (https://docs.python.org/3/glossary.html#term-free-threading).
]
test-requires = [ # Must be maintained identical to "dependency-groups".test
    "pytest >= 9.1",
]
test-command = "pytest {project}"

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_28"

[tool.cibuildwheel.macos]
before-all = "brew install libomp"
environment = { OpenMP_ROOT = "$(brew --prefix libomp)", MACOSX_DEPLOYMENT_TARGET = "14" }
#
# MACOSX_DEPLOYMENT_TARGET = Oldest MacOS version supported by the generated wheels.
# The version of the MacOS runner must be chosen accordingly.
#
# FIXME The availability of runners with "old" MacOS version on GitHub is not ensured,
# which limits the backward compatibility of the wheels produced with the current configuration.
